# Run cargo test and then trigger a build in OBS to build, test and publish an RPM
name: CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo test
      run: cargo test --verbose
    
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Webhook
        uses: zzzze/webhook-trigger@master
        with:
          data: ""
          webhook_url: ${{ secrets.OBS_TRIGGER_URL }}
          options: "--silent -H \"Authorization: Token ${{ secrets.OBS_TRIGGER_TOKEN }}\""
